package com.aadi.makelifegreat.ui.screens.life
import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.platform.LocalContext
import java.text.SimpleDateFormat
import java.util.*

private object LocalLifeStore{private const val N="mlg_notes";private const val R="mlg_run_total";fun notes(c:Context)=c.getSharedPreferences("life",0).getStringSet(N,emptySet())!!.toMutableList();fun save(c:Context,v:List<String>)=c.getSharedPreferences("life",0).edit().putStringSet(N,v.toSet()).apply();fun run(c:Context)=c.getSharedPreferences("life",0).getFloat(R,0f);fun addRun(c:Context,x:Float){val p=c.getSharedPreferences("life",0);p.edit().putFloat(R,p.getFloat(R,0f)+x).apply()}}
@Composable private fun Header(t:String,back:()->Unit){Row(verticalAlignment=Alignment.CenterVertically,modifier=Modifier.fillMaxWidth()){IconButton(back){Icon(Icons.Filled.ArrowBack,"Back")};Text(t,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black)}}
@Composable fun ScheduleScreen(onBack:()->Unit,onOpenRoutines:()->Unit,onOpenTodos:()->Unit){val day=SimpleDateFormat("EEEE, d MMM",Locale.getDefault()).format(Date());LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("My schedule",onBack)};item{Text(day,color=MaterialTheme.colorScheme.onSurfaceVariant)};item{SC("Morning","Wake → routine → breakfast",Icons.Filled.Alarm)};item{SC("School / class","Your scheduled class window",Icons.Filled.School)};item{SC("Study","Focus session + study workflow",Icons.Filled.Timer)};item{SC("Fitness","Run or home workout",Icons.Filled.DirectionsRun)};item{SC("Evening","Tasks → review → wind down",Icons.Filled.EditNote)};item{Button(onOpenRoutines,Modifier.fillMaxWidth()){Text("Manage timed routines & alarms")}};item{Button(onOpenTodos,Modifier.fillMaxWidth()){Text("Open today's tasks")}};item{Text("Exact alarms and sensitive device controls require the Android access you explicitly grant.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun SC(t:String,s:String,i:androidx.compose.ui.graphics.vector.ImageVector){Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),shape=RoundedCornerShape(20.dp)){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(i,null,tint=MaterialTheme.colorScheme.primary);Spacer(Modifier.width(12.dp));Column{Text(t,fontWeight=FontWeight.Bold);Text(s,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}
@Composable fun NotesScreen(onBack:()->Unit){val c=LocalContext.current;var notes by remember{mutableStateOf(LocalLifeStore.notes(c))};var draft by remember{mutableStateOf("")};Scaffold(floatingActionButton={FloatingActionButton(onClick={if(draft.isNotBlank()){notes=(notes+draft.trim()).toMutableList();LocalLifeStore.save(c,notes);draft=""}}){Icon(Icons.Filled.Add,"Add note")}}){p->LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Aadi Notes",onBack)};item{OutlinedTextField(draft,{draft=it},Modifier.fillMaxWidth(),label={Text("Write a note")},minLines=3)};items(notes.reversed()){n->Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(n);Text("Saved locally",style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}}}
@Composable fun FitnessScreen(onBack:()->Unit){val c=LocalContext.current;var km by remember{mutableStateOf("")};var total by remember{mutableStateOf(LocalLifeStore.run(c))};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Fitness",onBack)};item{Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.primaryContainer),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(20.dp)){Text("Running total");Text("%.1f km".format(total),style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Black);Text("Stored on this device",color=MaterialTheme.colorScheme.onSurfaceVariant)}}};item{OutlinedTextField(km,{km=it},Modifier.fillMaxWidth(),label={Text("Run distance (km)")})};item{Button(onClick={km.toFloatOrNull()?.takeIf{it>0}?.let{LocalLifeStore.addRun(c,it);total=LocalLifeStore.run(c);km=""}},Modifier.fillMaxWidth()){Icon(Icons.Filled.DirectionsRun,null);Spacer(Modifier.width(6.dp));Text("Save run")}};item{Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant)){Column(Modifier.padding(16.dp)){Text("Home workout",fontWeight=FontWeight.Bold);Text("Squats • push-ups • plank • mobility",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}}
@Composable fun MusicScreen(onBack:()->Unit){val c=LocalContext.current;var uri by remember{mutableStateOf<Uri?>(null)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri=it};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Header("Music",onBack);Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(18.dp)){Icon(Icons.Filled.MusicNote,null,tint=MaterialTheme.colorScheme.primary);Text("Offline music",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text(if(uri==null)"Pick an audio file stored on your phone"else"Selected audio file",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(10.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({picker.launch(arrayOf("audio/*"))}){Text("Choose song")};if(uri!=null)Button({c.startActivity(Intent(Intent.ACTION_VIEW,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION))}){Icon(Icons.Filled.PlayArrow,null);Text("Play")}}}};Text("The life system stays offline. Online music can remain in your normal music apps.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
